export const SCREEN = {
  PRODUCT_OVERVIEW: 'PRODUCT_OVERVIEW_SCREEN',
  PRODUCT_DETAIL: 'PRODUCT_DETAIL_SCREEN',
  CART: 'CART_SCREEN',
  ORDER: 'ORDER_SCREEN',

  DRAWER: 'DRAWER',

  USER_PRODUCTS: 'USER_PRODUCTS_SCREEN',
};
